# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20170318_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default=b'description', max_length=500),
        ),
    ]
