# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20170318_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
