# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20170318_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
