# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20170318_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
