# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20170318_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('book_photo', models.FileField(upload_to=b'')),
            ],
        ),
    ]
