# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 22:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0013_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('restaurant_photo', models.FileField(upload_to=b'')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(default=b'place', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(default=b'place', max_length=100),
        ),
    ]
