# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20170423_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default=b'null', max_length=255),
        ),
    ]
