# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_restaurant_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_photo',
            new_name='photo',
        ),
    ]
