# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_tutor'),
        ('service', '0016_auto_20170424_1140'),
    ]

    operations = [
    ]
