# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_auto_20170427_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default=b'description', max_length=255),
        ),
    ]
